// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAi9KH8n1u96KGCHTvjjcblZ_8x3QKyX-g',
    appId: '1:777980235435:web:1ef561b44be3b316c531ee',
    messagingSenderId: '777980235435',
    projectId: 'fir-admin-4f1fd',
    authDomain: 'fir-admin-4f1fd.firebaseapp.com',
    storageBucket: 'fir-admin-4f1fd.firebasestorage.app',
    measurementId: 'G-0HS65NMKVT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxP-FibxINH5lL4NjvK7R8woxN-mPyg48',
    appId: '1:777980235435:android:55a7067bbbcc2e64c531ee',
    messagingSenderId: '777980235435',
    projectId: 'fir-admin-4f1fd',
    storageBucket: 'fir-admin-4f1fd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZwRVDRQnTxp72ptdx3Gi05Y0z0yXvaIA',
    appId: '1:777980235435:ios:4fc378c9c8f555f8c531ee',
    messagingSenderId: '777980235435',
    projectId: 'fir-admin-4f1fd',
    storageBucket: 'fir-admin-4f1fd.firebasestorage.app',
    androidClientId: '777980235435-hecmlunrbt89j01kjrut620mcip4v02u.apps.googleusercontent.com',
    iosClientId: '777980235435-o4aaggnknm94o2vi74d4j1c0snsoa0df.apps.googleusercontent.com',
    iosBundleId: 'com.devans.firebaseAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZwRVDRQnTxp72ptdx3Gi05Y0z0yXvaIA',
    appId: '1:777980235435:ios:4fc378c9c8f555f8c531ee',
    messagingSenderId: '777980235435',
    projectId: 'fir-admin-4f1fd',
    storageBucket: 'fir-admin-4f1fd.firebasestorage.app',
    androidClientId: '777980235435-hecmlunrbt89j01kjrut620mcip4v02u.apps.googleusercontent.com',
    iosClientId: '777980235435-o4aaggnknm94o2vi74d4j1c0snsoa0df.apps.googleusercontent.com',
    iosBundleId: 'com.devans.firebaseAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAi9KH8n1u96KGCHTvjjcblZ_8x3QKyX-g',
    appId: '1:777980235435:web:15890dab18ca2ac0c531ee',
    messagingSenderId: '777980235435',
    projectId: 'fir-admin-4f1fd',
    authDomain: 'fir-admin-4f1fd.firebaseapp.com',
    storageBucket: 'fir-admin-4f1fd.firebasestorage.app',
    measurementId: 'G-22VKZSG6QB',
  );
}
