import 'package:freezed_annotation/freezed_annotation.dart';
import '../../domain/entities/settings_entity.dart';

part 'settings_state.freezed.dart'; // This will be generated by Freezed

@freezed
class SettingsState with _$SettingsState {
  const factory SettingsState.initial() = Initial;

  const factory SettingsState.loaded(AppThemeMode themeMode) = Loaded;

  const factory SettingsState.loading() = Loading;

  const factory SettingsState.error(String message) = Error;
}